PLUS = '+'
MINUS = '-'
MUL = '*'
DIV = '/'
FLOORDIV = '//'
MOD = '%'
POWER = '^'
ARITHMETIC_LEFT_SHIFT = '<<<'
ARITHMETIC_RIGHT_SHIFT = '>>>'
XOR = 'xor'
BINARY_ONES_COMPLIMENT = '~'
BINARY_LEFT_SHIFT = '<<'
BINARY_RIGHT_SHIFT = '>>'
AND = 'and'
OR = 'or'
NOT = 'not'
IN = 'in'
NOT_IN = 'not in'
IS = 'is'
IS_NOT = 'is not'
LPAREN = '('
RPAREN = ')'
LBRACK = '['
RBRACK = ']'
LBRACE = '{'
RBRACE = '}'
COMMA = ','
COLON = ':'
DOT = '.'
RANGE = '..'
ELLIPSIS = '...'
ARROW = '->'
CAST = 'as'
ASSIGN = '='
PLUS_ASSIGN = '+='
MINUS_ASSIGN = '-='
MUL_ASSIGN = '*='
DIV_ASSIGN = '/='
FLOORDIV_ASSIGN = '//='
MOD_ASSIGN = '%='
POWER_ASSIGN = '^='
PLUS_PLUS = '++'
MINUS_MINUS = '--'
EQUALS = '=='
NOT_BANG = '!'
NOT_EQUALS = '!='
LESS_THAN = '<'
GREATER_THAN = '>'
LESS_THAN_OR_EQUAL_TO = '<='
GREATER_THAN_OR_EQUAL_TO = '>='

ANY = 'any'
INT = 'int'
INT8 = 'i8'
INT16 = 'i16'
INT32 = 'i32'
INT64 = 'i64'
INT128 = 'i128'
UINT = 'uint'
UINT8 = 'u8'
UINT16 = 'u16'
UINT32 = 'u32'
UINT64 = 'u64'
UINT128 = 'u128'
DOUBLE = 'double'
FLOAT = 'float'
COMPLEX = 'complex'
STR = 'str'
BOOL = 'bool'
LIST = 'list'
TUPLE = 'tuple'
SET = 'set'
DICT = 'dict'
ENUM = 'enum'
FUN = 'fun'
FUNC = 'func'
STRUCT = 'struct'
OBJECT = 'object'

# Contstants
TRUE = 'true'
FALSE = 'false'
NULL = 'null'
INF = 'inf'

# Keywords
IF = 'if'
ELSE_IF = 'else if'
ELSE = 'else'
FOR = 'for'
WHILE = 'while'
SWITCH = 'switch'
CASE = 'case'
DEFAULT = 'default'
OPERATOR = 'operator'
EXTERN = 'extern'
CONST = 'const'
SELF = 'self'
RETURN = 'return'
BREAK = 'break'
FALLTHROUGH = 'fallthrough'
DEFER = 'defer'
CONTINUE = 'continue'
PASS = 'pass'
VOID = 'void'
TYPE = 'type'

ARITHMETIC_OP = (PLUS, MINUS, MUL, DIV, MOD, FLOORDIV, POWER, ARITHMETIC_LEFT_SHIFT, ARITHMETIC_RIGHT_SHIFT)

ASSIGNMENT_OP = (ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, FLOORDIV_ASSIGN, MOD_ASSIGN, POWER_ASSIGN, PLUS_PLUS, MINUS_MINUS)

ARITHMETIC_ASSIGNMENT_OP = (PLUS_ASSIGN, MINUS_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, FLOORDIV_ASSIGN, MOD_ASSIGN, POWER_ASSIGN)

INCREMENTAL_ASSIGNMENT_OP = (PLUS_PLUS, MINUS_MINUS)

COMPARISON_OP = (EQUALS, NOT_BANG, NOT_EQUALS, LESS_THAN, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO, IS, IS_NOT)

LOGICAL_OP = (AND, OR, NOT)

BINARY_OP = (XOR, BINARY_ONES_COMPLIMENT, BINARY_LEFT_SHIFT, BINARY_RIGHT_SHIFT)

MEMBERSHIP_OP = (IN, NOT_IN)

MULTI_WORD_OPERATORS = (IS, IS_NOT, IN, NOT_IN, NOT)

OPERATORS = (
                LPAREN, RPAREN, LBRACK, RBRACK, LBRACE, RBRACE,
                ARROW, COMMA, COLON, DOT, CAST, RANGE, ELLIPSIS,
) + ARITHMETIC_OP + ASSIGNMENT_OP + COMPARISON_OP + LOGICAL_OP + BINARY_OP + MEMBERSHIP_OP

SINGLE_OPERATORS = (
    LPAREN, RPAREN, LBRACK, RBRACK, LBRACE, RBRACE,
    BINARY_ONES_COMPLIMENT, COMMA
)

KEYWORDS = (
    IF, ELSE, WHILE, FOR, SWITCH, CASE, FUN, RETURN, BREAK, CONTINUE, PASS, VOID,
    CONST, DEFAULT, TYPE, FALLTHROUGH, DEFER
)

MULTI_WORD_KEYWORDS = (IF, ELSE, ELSE_IF)

TYPES = (ANY, INT, INT8, INT16, INT32, INT64, INT128, UINT, UINT8, UINT16, UINT32, UINT64, UINT128, DOUBLE, FLOAT, COMPLEX, STR, BOOL, LIST, TUPLE, DICT, ENUM, FUNC, LIST, TUPLE, STRUCT, OBJECT)

CONSTANTS = (TRUE, FALSE, NULL, INF)

PRINT = 'print'
INPUT = 'input'

BUILTIN_FUNCTIONS = (PRINT, INPUT)

LTYPE = 'LTYPE'
NUMBER = 'NUMBER'
STRING = 'STRING'
OP = 'OP'
CONSTANT = 'CONSTANT'
NEWLINE = 'NEWLINE'
INDENT = 'INDENT'
KEYWORD = 'KEYWORD'
ANON = 'ANON'
NAME = 'NAME'
EOF = 'EOF'
ALPHANUMERIC = 'alphanumeric'
NUMERIC = 'numeric'
OPERATIC = 'operatic'
WHITESPACE = 'whitespace'
COMMENT = 'comment'
ESCAPE = 'escape'
